import datetime
import html
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .models import Job

SOURCE_COLORS = {
    "MyJobMag": "#2563eb",
    "Corporate Staffing": "#0f766e",
    "DevNetJobs": "#b45309",
    "BrighterMonday": "#6d28d9",
    "Workable": "#0369a1",
    "Remotive": "#e11d48",
    "Jobicy": "#0e7490",
    "RemoteOK": "#7c3aed",
}


def _deadline_warn(deadline: str, today: datetime.date | None = None) -> bool:
    if not deadline:
        return False
    for fmt in ("%d %b %Y", "%Y-%m-%d", "%d %B %Y"):
        try:
            d = datetime.datetime.strptime(deadline, fmt).date()
            return (d - (today or datetime.date.today())).days <= 7
        except ValueError:
            continue
    return False


def plain_text(jobs: list[Job], date_str: str) -> str:
    lines = [
        f"JOB DIGEST - {date_str}",
        f"{len(jobs)} matching jobs (newest first)",
        "",
    ]
    for i, job in enumerate(jobs, 1):
        lines.append(f"{i}. {job.title}")
        if job.company:
            lines.append(f"   {job.company}")
        if job.location:
            lines.append(f"   Location: {job.location}")
        info = []
        if job.posted:
            info.append(f"Posted: {job.posted}")
        if job.deadline:
            info.append(f"Apply by: {job.deadline}")
        if info:
            lines.append("   " + "  |  ".join(info))
        if job.snippet:
            lines.append(f"   {job.snippet[:150]}...")
        lines.append(f"   {job.url}")
        lines.append("")
    return "\n".join(lines)


def _meta_div(meta: str) -> str:
    if not meta:
        return ""
    return (
        f"<div style='margin-top:4px;font-family:-apple-system,Segoe UI,Roboto,sans-serif;"
        f"font-size:12.5px;color:#64748b;'>{html.escape(meta)}</div>"
    )


def _dates_div(job: Job) -> str:
    parts = []
    if job.posted:
        parts.append(f"Posted {html.escape(job.posted)}")
    if job.deadline:
        urgent = _deadline_warn(job.deadline)
        color = "#dc2626" if urgent else "#334155"
        weight = "700" if urgent else "400"
        parts.append(
            f"<span style='color:{color};font-weight:{weight};'>"
            f"Apply by {html.escape(job.deadline)}"
            + (" ⚠" if urgent else "")
            + "</span>"
        )
    if not parts:
        return ""
    return (
        f"<div style='margin-top:5px;font-family:-apple-system,Segoe UI,Roboto,sans-serif;"
        f"font-size:12px;color:#64748b;'>{' &middot; '.join(parts)}</div>"
    )


def html_body(jobs: list[Job], date_str: str) -> str:
    rows = []
    for job in jobs:
        color = SOURCE_COLORS.get(job.source, "#6b7280")
        meta = " &middot; ".join(
            x for x in [job.company, job.location] if x
        )
        snippet = (
            f"<p style='margin:6px 0 0;font-size:13px;line-height:1.45;color:#475569;"
            f"font-family:Georgia,serif;'>{html.escape(job.snippet[:220])}</p>"
            if job.snippet
            else ""
        )
        rows.append(
            f"<a href='{html.escape(job.url, quote=True)}' "
            f"style='text-decoration:none;color:#1e293b;display:block;'>"
            f"<table role='presentation' cellpadding='0' cellspacing='0' border='0' "
            f"width='100%' style='margin:0 0 14px;'>"
            f"<tr><td style='background:#ffffff;border:1px solid #e2e8f0;border-left:4px solid {color};"
            f"border-radius:8px;padding:14px 18px;'>"
            f"<div style='margin-bottom:6px;'>"
            f"<span style='display:inline-block;font-family:-apple-system,Segoe UI,Roboto,sans-serif;"
            f"font-size:11px;font-weight:600;color:{color};letter-spacing:.06em;"
            f"text-transform:uppercase;'>{job.source}</span></div>"
            f"<div style='font-family:-apple-system,Segoe UI,Roboto,sans-serif;font-size:16px;"
            f"font-weight:700;color:#0f172a;line-height:1.3;'>{html.escape(job.title)}</div>"
            f"{_meta_div(meta)}"
            f"{_dates_div(job)}"
            f"{snippet}"
            f"</td></tr></table></a>"
        )

    return f"""<!doctype html><html><head><meta charset='utf-8'></head>
<body style='margin:0;padding:24px 0;background:#f1f5f9;'>
<div style='max-width:640px;margin:0 auto;font-family:-apple-system,Segoe UI,Roboto,sans-serif;'>
  <div style='background:#0f172a;border-radius:12px 12px 0 0;padding:22px 26px;'>
    <div style='font-size:20px;font-weight:800;color:#ffffff;letter-spacing:.02em;'>Daily Job Digest</div>
    <div style='font-size:13px;color:#94a3b8;margin-top:3px;'>{date_str} &middot; {len(jobs)} matching jobs &middot; newest first</div>
  </div>
  <div style='background:#ffffff;border-radius:0 0 12px 12px;padding:26px;'>
    {''.join(rows)}
  </div>
  <p style='font-size:11px;color:#94a3b8;margin:14px 6px;'>Auto-generated by job-digest. Sources: MyJobMag, Corporate Staffing Services, DevNetJobs, BrighterMonday, Workable, Remotive, Jobicy, RemoteOK.</p>
</div></body></html>"""


def send_email(sender: str, password: str, recipient: str, jobs: list[Job],
               date_str: str) -> None:
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Job Digest {date_str} - {len(jobs)} matching jobs"
    msg["From"] = f"Job Digest <{sender}>"
    msg["To"] = recipient

    msg.attach(MIMEText(plain_text(jobs, date_str), "plain", "utf-8"))
    msg.attach(MIMEText(html_body(jobs, date_str), "html", "utf-8"))

    with smtplib.SMTP("smtp.gmail.com", 587, timeout=60) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(sender, password)
        server.sendmail(sender, [recipient], msg.as_string())
    print(f"Email sent to {recipient}")


def today_str() -> str:
    return datetime.date.today().isoformat()